# Generated by Django 3.0.3 on 2020-04-26 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Flair_Detector_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file',
            new_name='files',
        ),
    ]
